#!/bin/bash
#SBATCH -J ssort            # job name
#SBATCH -o ssort.o          # output and error file name (%j expands to jobID)
#SBATCH -n 64               # total number of mpi tasks requested
#SBATCH -p normal           # queue (partition) -- normal, development, etc.
#SBATCH -t 00:10:00          # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=fang@cims.nyu.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
#SBATCH -A TG-ASC150003    # account number
mpirun ./compare_bcast 1000000 # run the MPI executable named a.out
